### ISSUE TITLE
GitLab Argo Bridge - Creates individual repository entry for each repo it works with

### ISSUE THREAD

**Issue by tylerauerbeck** [redhat-cop/tool-integrations#15]
Currently anytime the GitLab Argo Bridge creates an entry into `argocd-cm`, it creates a new repository for repo and key that it should use. While this causes a bit of a readability issue, it could also cause a data limit issue for particularly large uses cases (1 MB on etcd storage).

As of Argo 1.4.X, we have the ability to create a single entry per repo/org structure for credentials that can be used for multiple repos. To do this we can just do something like:

```
  repository.credentials: |
    - sshPrivateKeySecret:
        key: sshPrivateKey
        name: my-argo-bridge-key
      url: ssh://git@gitlab.com/my-org/my-group/
```

This would then allow for that single bridge key to be used for any repos under `my-org/my-group`. I think we still need to preserve the ability to specify different keys for different entries -- but I think this would significantly cut down on the number of keys/entries we need to manage.
